name: Feature Request
description: template for missing feature
title: '👌[feature]:'
labels:
  - enhancement
body:
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of the problem or missing capability
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: If you have a solution in mind, please describe it.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: Have you considered any alternative solutions or workarounds?
    validations:
      required: true
  - type: textarea
    id: lastwords
    attributes:
      label: Any last words?
      description: You can write additional informations
      value: 'no'
    validations:
      required: true
  - type: checkboxes
    id: check1
    attributes:
      label: >-
        I checked that there were no issue related and this issue is unique to
        this project
      options:
        - label: 'yes'
          required: true
  - type: checkboxes
    id: check2
    attributes:
      label: You didn't used any words that aren't appropriate
      options:
        - label: 'yes'
          required: true
  - type: markdown
    attributes:
      value: >-
        if this issue violates the github terms, you won't be able to write
        additional words or contributions to this repo and if it violates very
        badly then we will call github support and take the step of the report
        process
  - type: markdown
    attributes:
      value: Please make sure you're not violating the github rules and now submit!
  - type: markdown
    attributes:
      value: >-
        This template was generated with [Issue Forms
        Creator](https://issue-forms-creator.netlify.app)
