name: Deploy Quartz site

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'README.md'
      - '.github/workflows/deploy.yml'
      - 'quartz.config.ts'
      - 'quartz.layout.ts'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Prepare content
        run: |
          mkdir -p content
          rm -rf content/docs
          cp -r docs content/docs
          TITLE=$(grep -m1 '^## ' README.md | sed 's/^## //')
          echo -e "---\ntitle: \"${TITLE}\"\n---\n" > content/index.md
          cat README.md >> content/index.md

      - name: Build Quartz using Docker
        run: |
          docker pull ghcr.io/jackyzha0/quartz:sha-f14260b
          docker run --rm -v ./content:/usr/src/app/content -v ./public:/usr/src/app/public ghcr.io/jackyzha0/quartz:sha-f14260b build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
