name: Deploy Workflow

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'README.md'
      - '.github/workflows/deploy.yml'
      - 'docusaurus.config.js'
      - 'package.json'
      - 'sidebars/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 레포지토리 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Node.js 설치
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # 3. 의존성 설치
      - name: Install dependencies
        run: npm install

      # 4. docs 폴더 준비 (Docusaurus docs 폴더로 복사)
      - name: Prepare docs
        run: |
          mkdir -p docusaurus_docs
          rm -rf docusaurus_docs/*
          cp -r docs/* docusaurus_docs/

          # README.md 첫 번째 heading → index.md 제목
          TITLE=$(grep -m1 '^## ' README.md | sed 's/^## //')
          echo -e "---\ntitle: \"${TITLE}\"\n---\n" > docusaurus_docs/index.md
          cat README.md >> docusaurus_docs/index.md

      # 5. Docusaurus docs 폴더 교체
      - name: Replace Docusaurus docs
        run: |
          rm -rf docs
          mv docusaurus_docs docs

      # 6. 사이트 빌드
      - name: Build Docusaurus site
        run: npm run build

      # 7. GitHub Pages 배포
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
